<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQSOMeYQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQSOMeYQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQSOMeYQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQSOMeYQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQSOMeYQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'QSOMeYQ',
    'container.build_id' => '3fd7ec86',
    'container.build_time' => 1580929115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQSOMeYQ');
